-- Spring Data JDBC lesson (31): JPA ddl-auto does not create this table.
-- Unquoted identifiers match Spring Data JDBC / H2 default uppercase resolution.
CREATE TABLE IF NOT EXISTS SD31_SHIPMENTS (
    ID BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TRACKING_CODE VARCHAR(255)
);
