-- Spring Data JDBC lesson (31): JPA ddl-auto does not create this table.
CREATE TABLE IF NOT EXISTS sd31_shipments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_code VARCHAR(255)
);
