CREATE TABLE IF NOT EXISTS acl_sid (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    principal BOOLEAN NOT NULL,
    sid VARCHAR(100) NOT NULL,
    CONSTRAINT uk_acl_sid UNIQUE (sid, principal)
);
CREATE TABLE IF NOT EXISTS acl_class (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    class VARCHAR(100) NOT NULL,
    class_id_format VARCHAR(10),
    CONSTRAINT uk_acl_class UNIQUE (class)
);
CREATE TABLE IF NOT EXISTS acl_object_identity (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    object_id_class BIGINT NOT NULL,
    object_id_identity VARCHAR(36) NOT NULL,
    parent_object BIGINT,
    owner_sid BIGINT,
    entries_inheriting BOOLEAN NOT NULL,
    CONSTRAINT uk_acl_objid UNIQUE (object_id_class, object_id_identity),
    FOREIGN KEY (parent_object) REFERENCES acl_object_identity(id)
);
CREATE TABLE IF NOT EXISTS acl_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acl_object_identity BIGINT NOT NULL,
    ace_order INT NOT NULL,
    sid BIGINT NOT NULL,
    mask INTEGER NOT NULL,
    granting BOOLEAN NOT NULL,
    audit_success BOOLEAN NOT NULL,
    audit_failure BOOLEAN NOT NULL,
    FOREIGN KEY (acl_object_identity) REFERENCES acl_object_identity(id),
    FOREIGN KEY (sid) REFERENCES acl_sid(id)
);
